version: '1.0'
services:
  app:
    image: user-management-service
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Sample123$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - C:\Users\Owen\DockerVolumes\sqlserver:/var/opt/mssql/data